feat(ui): add an icon chatbot
okp4/okp4-web pull request #221
Opened 2023-12-18 11:28 UTC by JulienMassonnat

I added a small rounded icon on the right bottom corner to link to our OKP4GPT. 
I've also added some smooth animations. Below you can find the icon in a screencapture and a short video with the animations.

![image](https://github.com/okp4/okp4-web/assets/63841183/ae6cbce1-4c8b-4cc2-b9a6-e80a1039531f)
https://github.com/okp4/okp4-web/assets/63841183/8e6ac26a-d1a3-4845-b950-fd34e98263bb

2023-12-18 12:59 UTC, MdechampG approved these changes
Great ! Just a little remark : it's a bit strange that it continuously blurring and unblurring when the mouse is on the logo. Maybe it's possible not to redo indefinitely the animation ?

2023-12-18 13:36 UTC, JulienMassonnat commented
Is it better ? 

https://github.com/okp4/okp4-web/assets/63841183/5184c7a5-9893-40d1-ba4e-7b8ec87eee4a

2023-12-18 13:38 UTC, MdechampG commented
> Is it better ?
> 
>  2023-12-18.14-35-36.mp4

Yes it's better thank you !

2023-12-18 13:42 UTC, JulienMassonnat commented
I added a new commit to modify with Marine's comment

2023-12-18 13:58 UTC, ccamel requested changes
Some minor remarks.

2023-12-18 13:58 UTC, ccamel commented on src/assets/styles/transversals/_footer.scss
> +  position: relative; /* Ajout pour le positionnement du texte */
Remove all the comments (unecessary).

2023-12-18 13:58 UTC, ccamel commented on src/assets/styles/transversals/_footer.scss
> +}
Remove duplicated properties.

```suggestion
.chatBotText {
  font-family: 'Norse';
  font-size: 25px;
  width: 120px;
  color: white;
  text-align: center;
  border-radius: 5px;
  padding: 5px 0;
  z-index: 99;
  margin-left: -60px;
  display: inline-block;
  visibility: hidden;
  opacity: 0;
  position: absolute;
  bottom: 100%;
  left: 50%;
  transform: translateX(-80%);
  transition: visibility 0s, opacity 0.5s linear;
}
```

2023-12-18 14:00 UTC, JulienMassonnat commented on src/assets/styles/transversals/_footer.scss
> +  position: relative; /* Ajout pour le positionnement du texte */
Ok thanks

2023-12-18 14:00 UTC, JulienMassonnat commented on src/assets/styles/transversals/_footer.scss
> +}
Ok thanks ;)

2023-12-18 14:01 UTC, ccamel commented on src/components/Footer.js
> +        onKeyDown={handleKeyDown}
You should remove this line.

2023-12-18 15:05 UTC, JulienMassonnat commented
Thanks @ccamel I changed the behavior.
On smartphone it's displayed only inside the burger menu
![image](https://github.com/okp4/okp4-web/assets/63841183/3ae3c442-a8df-4837-aad6-f0e88832b758)
On desktop it's an icon chatbot as seen previously

2023-12-19 07:27 UTC, ccamel approved these changes
Awesome! :+1:

2023-12-19 07:33 UTC, merged